#!/bin/sh
#
# Update the mailing list archive.  Should be run every day.
# This command must be run in the current directory.
#

set -x
dir=/home/mercury/public/mailing_lists/

day=`date '+%d'`
month=`date '+%m'`
year=`date '+%y'`

if [ $day = "01" ]
then
    month=`expr $month - 1`
    month=`printf "%02d\n" $month`
fi

for mail in mercury-users mercury-developers
do
    ./archive2html.sh -d $dir -f $mail -m $month -y $year
done
