#-----------------------------------------------------------------------------#
# Copyright (C) 1998 University of Melbourne.
# This file may only be copied under the terms of the GNU General
# Public License - see the file COPYING in the Mercury distribution.
#-----------------------------------------------------------------------------#

PHP3=/usr/lib/cgi-bin/php3 -q
CP=cp -afu

#-----------------------------------------------------------------------------#

vpath %.inc ./include
vpath %.inc $(ROOT)/include
vpath %.inc $(ROOT)/news

$(HTML): %.html: %.php3 %.inc globals.inc menubar.inc template.inc functions.inc

#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#


.PHONY: html
html: $(HTML)
ifdef DIRS
	for dir in $(DIRS); 				\
	do 						\
		if [ -d $$dir ]; then			\
			(cd $$dir && $(MAKE) html);	\
		fi					\
	done
endif

.PHONY: all
all: $(HTML)
ifdef DIRS
	for dir in $(DIRS); 				\
	do 						\
		if [ -d $$dir ]; then			\
			(cd $$dir && $(MAKE) all);	\
		fi					\
	done
endif


.PHONY: install
install: html
	[ -d $(INSTALL_WEBDIR) ] || mkdir -p $(INSTALL_WEBDIR)
	$(CP) $(HTML) $(INSTALL_WEBDIR)/
ifdef DIRS
	for dir in $(DIRS);						\
	do				        			\
		[ -d $(INSTALL_WEBDIR)/$$dir ] ||			\
			mkdir -p $(INSTALL_WEBDIR)/$$dir;		\
		(export INSTALL_WEBDIR=$(INSTALL_WEBDIR)/$$dir &&	\
		cd $$dir && $(MAKE) install);				\
	done
endif
	chmod a+r,g+w $(INSTALL_WEBDIR)/*
	chgrp mercury $(INSTALL_WEBDIR)/*

.PHONY: clean
clean:
	-rm -f $(HTML)
ifdef DIRS
	for dir in $(DIRS);				\
	do				        	\
		if [ -d $$dir ]; then			\
			(cd $$dir && $(MAKE) clean);	\
		fi					\
	done
endif

.PHONY: touch
touch:
	touch *.php3

#-----------------------------------------------------------------------------#

%.html: %.php3
	$(PHP3) $< > $@

#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
