#-----------------------------------------------------------------------------#
# Copyright (C) 1995 University of Melbourne.
# This file may only be copied under the terms of the GNU General
# Public License - see the file COPYING in the Mercury distribution.
#-----------------------------------------------------------------------------#

PHP3=/usr/lib/cgi-bin/php3

#-----------------------------------------------------------------------------#

vpath %.inc ./include
vpath %.inc $(ROOT)/include
vpath %.inc $(ROOT)/news

$(HTML): %.html: %.php3 %.inc menubar.inc template.inc functions.inc

#-----------------------------------------------------------------------------#

#-----------------------------------------------------------------------------#


.PHONY: html
html: $(HTML)
ifdef DIRS
	for dir in $(DIRS); 				\
	do 						\
		(cd $$dir; $(MAKE) html); 		\
	done
endif

.PHONY: all
all: $(HTML)
ifdef DIRS
	for dir in $(DIRS); 				\
	do 						\
		(cd $$dir; $(MAKE) all); 		\
	done
endif


.PHONY: install
install: $(HTML)
	[ -d $(INSTALL_WEBDIR) ] || mkdir -p $(INSTALL_WEBDIR)
	cp -a $(HTML) $(INSTALL_WEBDIR)/
ifdef DIRS
	for dir in $(DIRS);					\
	do				        		\
		(export INSTALL_WEBDIR=$(INSTALL_WEBDIR)/$$dir;	\
		cd $$dir; $(MAKE) install);			\
	done
endif
	chmod a+r,g+w $(INSTALL_WEBDIR)/*
	chgrp mercury $(INSTALL_WEBDIR)/*

.PHONY: clean
clean:
	-rm -f $(HTML)
ifdef DIRS
	for dir in $(DIRS);			\
	do				        \
		(cd $$dir; $(MAKE) clean);	\
	done
endif

.PHONY: touch
touch:
	touch *.php3

#-----------------------------------------------------------------------------#

%.html: %.php3
	$(PHP3) $< | sed 's/Content-type:.*//g'> $@

#-----------------------------------------------------------------------------#
#-----------------------------------------------------------------------------#
