<h2>Developer Documentation</h2>

<!------
% Put this back in when there are PostScript version online.
The HTML versions are set up for browsing, however, if you'd prefer a
copy of the entire document, links to postscript copies are provided.
Please note that the postscript files are compressed using gzip and are
in a4 format.
-------->
<p>
<ul>
<li> 	<strong>Developer Introduction</strong> <br>
	Tips and tricks for developers just starting to work with
	the Mercury source code.<p>

	Available in 
	<a href="developers/developer_intro.html">HTML</a>
	<p>

<li> 	<strong>Remote CVS Access</strong> <br>
	How to access the CVS repository from your machine.<p>

	Available in 
	<a href="developers/remote_cvs.html">HTML</a>
	<p>

<li> 	<strong>C Coding Standard For The Mercury Project</strong> <br>
	The standard used for the C source in the Mercury compiler. <p>

	Available in 
	<a href="developers/c_coding_standard.html">HTML</a>
	<p>

<li>	<strong>Reviews</strong> <br>
	Outlines reviewing procedure. <p>

	Available in
	<a href="doc-latest/reviews.html">HTML</a> and 
	<a href="doc-latest/reviews.text">Plain text</a>
	<p>

<li>	<strong>Mercury Coding Standards</strong> <br>
	Standard for Mercury code. <p>

	Available in
	<a href="doc-latest/coding_standards.html">HTML</a> and 
	<a href="doc-latest/coding_standards.text">Plain text</a>
	<p>

<li>	<strong>Compiler Design</strong> <br>
	Details of the compiler design. <p>

	Available in
	<a href="doc-latest/compiler_design.html">HTML</a> and
	<a href="doc-latest/compiler_design.text">Plain text</a>
	<p>

<li>	<strong>Allocation</strong> <br>
	Details of the allocation scheme currently being implemented. <p>

	Available in
	<a href="doc-latest/allocation.html">HTML</a> and
	<a href="doc-latest/allocation.text">Plain text</a>
	<p>

<li>	<strong>Release checklist</strong> <br>
	The release procedure. <p>

	Available in
	<a href="doc-latest/release_checklist.html">HTML</a> and
	<a href="doc-latest/release_checklist.text">Plain text</a>
	<p>

<li>	<strong>Garbage collection and C code</strong> <br>
	<p>

	Available in
	<a href="doc-latest/gc_and_c_code.html">HTML</a> and
	<a href="doc-latest/gc_and_c_code.text">Plain text</a>
	<p>

<li>	<strong>Glossary</strong> <br>
	Terms used in the Mercury implementation.  <p>

	Available in
	<a href="doc-latest/glossary.html">HTML</a> and
	<a href="doc-latest/glossary.text">Plain text</a>
	<p>

<li>	<strong>To do list</strong> <br>
	Things still to do in the Mercury project.  <p>

	Available in
	<a href="doc-latest/todo.html">HTML</a> and
	<a href="doc-latest/todo.text">Plain text</a>
	<p>

<li>	<strong>Work in progress</strong> <br>
	Things currently being done on the Mercury project.  <p>

	Available in
	<a href="doc-latest/work_in_progress.html">HTML</a> and
	<a href="doc-latest/work_in_progress.text">Plain text</a>
	<p>

<li>	<strong>Bootstrapping</strong> <br>
	What to do when a change requires bootstrapping. <p>

	Available in
	<a href="doc-latest/bootstrapping.html">HTML</a>
	<p>

<li>	<strong>HOWTO add a new user.</strong> <br>
	Information on what needs to be done when a new person joins the
	Mercury project.  <p>

	Available in
	<a href="developers/add_new_user.html">HTML</a>
	<p>

<!---------
%% Take this out of comments when the bytecode docs have settled down a bit.
<li>	<strong>Bytecode</strong> <br>
	Information on the Mercury bytecode.  <p>

	Available in
	<a href="developers/bytecode.html">HTML</a>
	<p>
-------->

</ul>
<p>
