<h2>Developer Documentation</h2>

<!------
% Put this back in when there are PostScript version online.
The HTML versions are set up for browsing, however, if you'd prefer a
copy of the entire document, links to postscript copies are provided.
Please note that the postscript files are compressed using gzip and are
in a4 format.
-------->
<p>
<ul>
<li> 	<strong>C Coding Standard For The Mercury Project</strong> <br>
	The standard used for the C source in the Mercury compiler. <p>

	Available in 
	<a href="c_coding_standard.html">HTML</a>
	<p>

<li>	<strong>Reviews</strong> <br>
	Outlines reviewing procedure. <p>

	Available in
	<a href="reviews.html">HTML</a> and 
	<a href="reviews.text">Plain text</a>
	<p>

<li>	<strong>Mercury Coding Standards</strong> <br>
	Standard for Mercury code. <p>

	Available in
	<a href="coding_standards.html">HTML</a> and 
	<a href="coding_standards.text">Plain text</a>
	<p>

<li>	<strong>Compiler Design</strong> <br>
	Details of the compiler design. <p>

	Available in
	<a href="compiler_design.html">HTML</a> and
	<a href="compiler_design.text">Plain text</a>
	<p>

<li>	<strong>Allocation</strong> <br>
	Details of the allocation scheme currently being implemented. <p>

	Available in
	<a href="allocation.html">HTML</a> and
	<a href="allocation.text">Plain text</a>
	<p>

<li>	<strong>Module system</strong> <br>
	Details of the module system. <p>

	Available in
	<a href="module_system.html">HTML</a> and
	<a href="module_system.text">Plain text</a>
	<p>

<li>	<strong>Release checklist</strong> <br>
	The release procedure. <p>

	Available in
	<a href="release_checklist.html">HTML</a> and
	<a href="release_checklist.text">Plain text</a>
	<p>

<li>	<strong>Garbage collection and C code</strong> <br>
	<p>

	Available in
	<a href="gc_and_c_code.html">HTML</a> and
	<a href="gc_and_c_code.text">Plain text</a>
	<p>

<li>	<strong>Glossary</strong> <br>
	Terms used in the Mercury implementation.  <p>

	Available in
	<a href="glossary.html">HTML</a> and
	<a href="glossary.text">Plain text</a>
	<p>

<li>	<strong>To do list</strong> <br>
	Things still to do in the Mercury project.  <p>

	Available in
	<a href="todo.html">HTML</a> and
	<a href="todo.text">Plain text</a>
	<p>

<!---------
%% Take this out of comments when the bytecode docs have settled down a bit.
<li>	<strong>Bytecode</strong> <br>
	Information on the Mercury bytecode.  <p>

	Available in
	<a href="bytecode.html">HTML</a>
	<p>
-------->

</ul>
<p>
