<h2>Mercury Documentation</h2>

The HTML versions are set up for browsing, however, if you'd prefer a
copy of the entire document, links to postscript copies are provided.
Please note that the postscript files are compressed using gzip and are
in a4 format.
<p>
<ul>
	<li> <a href="mailto:rwab1@cam.sri.com">Ralph Becket</a>'s
	     <strong>Mercury tutorial</strong><br>
	A beginner's introduction to Mercury.
	This is still under development. 
	Feedback would be appreciated.
	<p>

	Available in
	<a href="../tutorial/index.html">HTML</a> only.
	<p>

	<li> <strong>Mercury Language Reference Manual</strong> <br>
	Information on the Mercury programming language
	itself, including syntax, types and modes, determinism, 
	the module system, foreign language interface and higher-order
	programming.<p>

	Available in 
	<a href="doc/reference_manual_toc.html">HTML</a> or
	<a href="doc/reference_manual.ps.gz">Postscript</a>
	<p>

	<li> <strong>Mercury User's Guide</strong><br>
	Information on the Mercury compiler, including
	how to compile, using multiple modules, profiling, debugging,
	and compilation options. <p>

	Available in 
	<a href="doc/user_guide_toc.html">HTML</a> or
	<a href="doc/user_guide.ps.gz">Postscript</a>
	<p>

	<li> <strong>Mercury Library Reference Manual</strong><br>
	Descriptions of the interfaces to the library
	which comes with the Mercury distribution.<p>

	Available in 
	<a href="doc/library_toc.html">HTML</a> or
	<a href="doc/library.ps.gz">Postscript</a>
	<p>

	<li> <strong>Prolog to Mercury Transition Guide</strong><br>
	Information to assist programmers to move Prolog
	programs to Mercury. Includes information on differences in
	the languages and common programming styles.<p>

	Available in 
	<a href="doc/transition_guide_toc.html">HTML</a> or
	<a href="doc/transition_guide.ps.gz">Postscript</a>
	<p>

	<li> <strong>Frequently Asked Questions</strong><br>
	Information on common programming errors, problems caused by
	unimplemented Mercury features and where to turn for help.<p>
	Now implemented using FAQ-O-Matic.
	<p>
	Enter the 
	<a href="http://hydra.cs.mu.oz.au/cgi-bin/fom">FAQ</a>.
	<p>
</ul>
