<?

/* 
** This is the MCORBA news database.
**
** Add new items at the top in chronological order.
**
** Each item consists of
**	date =>
**	array( title,
**	    description
**	),
** Make sure you put a comma between each item, and an arrow
** between the date and the news.
*/

$mcorba_newsdb = array(

"23 Sep 1998" => array("MCORBA 0.1 available for download.",

"The first release of MCORBA has been placed on the web site for
download.  It is not yet complete, but enough is there that you
can see what transformations are done.  The most important thing
that is missing at the moment is the generation of some of the
C++ code."
),

"21 Sep 1998" => array("MCORBA web page added.",

"We've just added this page to the Mercury web pages."
)

);

?>


