<?

/* 
** This is the MCORBA news database.
**
** Add new items at the top in chronological order.
**
** Each item consists of
**	date =>
**	array( title,
**	    description
**	),
** Make sure you put a comma between each item, and an arrow
** between the date and the news.
*/

$mcorba_newsdb = array(

"9 Sep 1998" => array("MCORBA web page added.",

"We've just added this page to the Mercury web pages."
)

);

?>


