<?

/* 
** This is the reports news database.
**
** Add new items at the top in chronological order.
**
** Each item consists of
**	date => array(filename, description)
** Make sure you put a comma between each item and an arrow between the
** date and the filename.
*/

$reportsdb = array(
	"3 August 2001" =>
		array("minutes_03_08_01.html", "Mercury Meeting Minutes"),
	"20 July 2001" =>
		array("minutes_20_07_01.html", "Mercury Meeting Minutes"),
	"29 June 2001" =>
		array("minutes_29_06_01.html", "Mercury Meeting Minutes"),
	"22 June 2001" => 
		array("minutes_22_06_01.html", "Mercury Meeting Minutes"),
	"25 May 2001" => 
		array("minutes_25_05_01.html", "Mercury Meeting Minutes"),
	"18 May 2001" => 
		array("minutes_18_05_01.html", "Mercury Meeting Minutes"),
	"11 May 2001" => 
		array("minutes_11_05_01.html", "Mercury Meeting Minutes"),
	"4 May 2001" =>
		array("minutes_04_05_01.html", "Mercury Meeting Minutes"),
	"27 April 2001" => 
		array("minutes_27_04_01.html", "Mercury Meeting Minutes"),
	"20 April 2001" => 
		array("minutes_20_04_01.html", "Mercury Meeting Minutes"),
	"7 April 2001" => 
		array("minutes_07_04_01.html", "Mercury Meeting Minutes"),
	"30 March 2001" => 
		array("minutes_30_03_01.html", "Mercury Meeting Minutes"),
	"16 March 2001" => 
		array("minutes_16_03_01.html", "Mercury Meeting Minutes"),
	"9 March 2001" => 
		array("minutes_09_03_01.html", "Mercury Meeting Minutes"),
	"2 March 2001" => 
		array("minutes_02_03_01.html", "Mercury Meeting Minutes"),
	"16 Feb 2001" => 
		array("minutes_16_02_01.html", "Mercury Meeting Minutes"),
	"9 Feb 2001" => 
		array("minutes_09_02_01.html", "Mercury Meeting Minutes"),
	"2 Feb 2001" => 
		array("minutes_02_02_01.html", "Mercury Meeting Minutes"),
	"19 Jan 2001" => 
		array("minutes_19_01_01.html", "Mercury Meeting Minutes"),
	"12 Jan 2001" => 
		array("minutes_12_01_01.html", "Mercury Meeting Minutes"),
	"5 Jan 2001" => 
		array("minutes_05_01_01.html", "Mercury Meeting Minutes"),
	"15 Dec 2000" => 
		array("minutes_15_12_00.html", "Mercury Meeting Minutes"),
	"08 Dec 2000" => 
		array("minutes_08_12_00.html", "Mercury Meeting Minutes"),
	"01 Dec 2000" => 
		array("minutes_01_12_00.html", "Mercury Meeting Minutes"),
	"24 Nov 2000" => 
		array("minutes_24_11_00.html", "Mercury Meeting Minutes"),
	"17 Nov 2000" => 
		array("minutes_17_11_00.html", "Mercury Meeting Minutes"),
	"20 Oct 2000" => 
		array("minutes_20_10_00.html", "Mercury Meeting Minutes"),
	"13 Oct 2000" => 
		array("minutes_13_10_00.html", "Mercury Meeting Minutes"),
	"6 Oct 2000" => 
		array("minutes_06_10_00.html", "Mercury Meeting Minutes"),
	"29 Sep 2000" => 
		array("minutes_29_09_00.html", "Mercury Meeting Minutes")
);

?>


