<?

/* 
** This is the reports news database.
**
** Add new items at the top in chronological order.
**
** Each item consists of
**	date => array(filename, description)
** Make sure you put a comma between each item and an arrow between the
** date and the filename.
*/

$reportsdb = array(
	"01 Dec 2000" => 
		array("minutes_01_12_00.html", "Mercury Meeting Minutes"),
	"24 Nov 2000" => 
		array("minutes_24_11_00.html", "Mercury Meeting Minutes"),
	"17 Nov 2000" => 
		array("minutes_17_11_00.html", "Mercury Meeting Minutes"),
	"20 Oct 2000" => 
		array("minutes_20_10_00.html", "Mercury Meeting Minutes"),
	"13 Oct 2000" => 
		array("minutes_13_10_00.html", "Mercury Meeting Minutes"),
	"6 Oct 2000" => 
		array("minutes_06_10_00.html", "Mercury Meeting Minutes"),
	"29 Sep 2000" => 
		array("minutes_29_09_00.html", "Mercury Meeting Minutes")
);

?>


