<H2>Download<span class="submenutitle">/ license</span></H2>

<p>
The Mercury implementation is free software, but it is Copyright
(C) 1993-2013 The University of Melbourne.  It is distributed
under the terms of the
<a href="http://www.gnu.org/licenses/gpl-2.0.html">GNU General Public License (GPL)</a>.
See the file <a href="/download/COPYING">COPYING</a> for copying permission.
</p>

<p>
The Mercury libraries and runtime (the files in the library, trace,
browser, ssdb, mdbcomp and runtime subdirectories) are distributed
under the terms of the
<a href="http://www.gnu.org/licenses/lgpl-2.0.html">GNU Library General Public License (LGPL)</a>.
See the file <a href="/download/COPYING.LIB">COPYING.LIB</a> for copying permissions for those files.
</p>
