<h2>Old Releases</h2>

The Mercury distribution has been released to the public several times.
The release information pages for these older releases may contain
useful information, including release notes and known problems,
sometimes with work-arounds or patches.   If you are experiencing
problems with these releases, it might be worth installing the <a
href="release.html">current release</a>
<p>

Please note, however, that the source and binaries for these
releases are often no longer available from the FTP site.

<h3>Release 0.7.3</h3>

On the 1st November, 1997, we released Mercury 0.7.3. Some installation
problems with Windows, problems with the profiler and compatibility with
GNU Make versions >= 3.76 were fixed.  A few features were also added.

<h3>Release 0.7.2</h3>

On the 13th October, 1997 we released Mercury 0.7.2. This release fixed
a few bugs, and added quite a few new features. Support was added
for user-defined equality predicates and generalized trailing.
We also split the distribution into "core" and "extras".

<h3>Release 0.7</h3>

On 15th August, 1997 we released Mercury 0.7.<p>

<ul>
	<li>
	<a href = "release-0.7.html">
	Release notes for 0.7
	</a>

	<li>
	<a href = "release-0.7-contents.html">
	Contents of release 0.7 distribution
	</a>

	<li>
	<a href = "release-0.7-bugs.html">
	Known problems with release 0.7
	</a>

	<li>
	<a href = "limitations.html">
	Limitations of the current release.
	</a>
</ul>

<h4>Source Distribution of Mercury 0.7</h4>

<dl>
<dt>
The full source distribution is 4.8Mb.<br>
<dd> Distribution:
<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/mercury-0.7.tar.gz">Australia</a>
<a href = "ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/mercury-0.7.tar.gz">USA</a>
<a href = "ftp://ftp.csd.uu.se/pub/Mercury/mercury-0.7.tar.gz">Europe</a>
</dl>

<h4>Binary Distribution of Mercury 0.7</h4>

<dl>
    <dt>x86 machines running Linux (ELF executable format) (4.9Mb):
	<dd> Distribution:
<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/mercury-0.7.i386-linux-ELF.tar.gz">Australia</a>
<a href = "ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/mercury-0.7.i386-linux-ELF.tar.gz">USA</a>
<a href = "ftp://ftp.csd.uu.se/pub/Mercury/mercury-0.7.i386-linux-ELF.tar.gz">Europe</a>
	<p>

    <dt>Sun SPARC machines running Solaris 2.x and SunOS 5.x (5.5Mb):
	<dd> Distribution:
<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/mercury-0.7.sparc-sun-solaris.tar.gz">Australia</a>
<a href = "ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/mercury-0.7.sparc-sun-solaris.tar.gz">USA</a>
<a href = "ftp://ftp.csd.uu.se/pub/Mercury/mercury-0.7.sparc-sun-solaris.tar.gz">Europe</a>

	<p>
    <dt>DEC Alpha machines running OSF/1 or Digital Unix (11.2Mb):
	<dd> Distribution:
<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/mercury-0.7.alpha-dec-osf.tar.gz">Australia</a>
<a href = "ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/mercury-0.7.alpha-dec-osf.tar.gz">USA</a>
<a href = "ftp://ftp.csd.uu.se/pub/Mercury/mercury-0.7.alpha-dec-osf.tar.gz">Europe</a>

	<p>
    <dt>x86 machines running Windows 95 or Windows NT (2.9Mb):
	<dd> Distribution:
<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/mercury-0.7.i386-windows.tar.gz">Australia</a>

</dl>

<h4>FTP Sites for Mercury 0.7</h4>
<dl>
	<dt> Australia: 

	<dd>
	<a href = "ftp://turiel.cs.mu.OZ.AU/pub/mercury/">
	ftp://turiel.cs.mu.OZ.AU/pub/mercury/</a>

	<dt> USA:
	<dd>
	<a href = "ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/">
	ftp://ftp.cs.sunysb.edu/pub/XSB/mercury/</a>

	<dt> Europe:
	<dd>
	<a href = "ftp://ftp.csd.uu.se/pub/Mercury/">
	ftp://ftp.csd.uu.se/pub/Mercury/</a>
</dl>

<h3>Release 0.6.2-1</h3>

On the 2nd of June, 1997, Debian GNU/Linux 1.3 was released, including a
slightly modified Mercury 0.6.2 as one of the stable development
packages.  Thanks to Milan Zamazal (pdm@fi.muni.cz) for preparing this
package.  This package can be obtained at any of the Debian mirrors -
see the <a href="http://www.debian.org">Debian Web Site</a> for more
information on Debian.  It will also be available on any official Debian
1.3 CDs.  Please note: this Debian version "mercury 0.6.2-1" uses a
different name for the Mercury compiler `mc' due to name clashes with
another package, so the documentation (user's guide in particular)
should read `mercury' instead of `mc'.  This problem will be fixed in
Mercury 0.7.

<h3>Release 0.6.2</h3>

On the 14th of January, 1997 an updated version of the binary
distribution of Mercury for Windows 95/NT was released.  That was
still a beta release of Windows support.  That release was version 0.6.2.<p>

<h3>Release 0.6.1</h3>

On 26th of August, 1996, a patch for a problem with integer
multiplication and division was made available (see the <a href=
"release-0.6-bugs.html">known problems list</a> for details, and patches
for both the source and binary distributions).  
The version of Mercury 0.6 with these patches applied to is referred to
as 0.6.1.<p>

<h3>Release 0.6</h3>

This distribution of Mercury was released on 2nd of August, 1996.<p>

<ul>
	<li>
	<a href = "release-0.6.html">
	Release notes for 0.6
	</a>

	<li>
	<a href = "release-0.6-contents.html">
	Contents of release 0.6 distribution
	</a>

	<li>
	<a href = "release-0.6-bugs.html">
	Known problems with release 0.6
	</a>
</ul>

<h3>Release 0.5.1</h3>

This distribution of Mercury was a bug fix release, for problems found
in 0.5.

<ul>
	<li>
	<a href = "release-0.5.1.html">
	Release notes for 0.5.1 
	</a>

	<li>
	<a href = "release-0.5.1-bugs.html">
	Known problems with release 0.5.1
	</a>
</ul>

<h3>Release 0.5</h3>

This distribution of Mercury was released on 15 February 1996.

<ul>
	<li>
	<a href = "release-0.5.html">
	Release notes for 0.5
	</a>

	<li>
	<a href = "release-0.5-contents.html">
	Contents of release 0.5 distribution
	</a>

	<li>
	<a href = "release-0.5-bugs.html">
	Known problems with release 0.5
	</a>
</ul>

<h3>Release 0.4</h3>

This distribution of Mercury was released on 15 September 1995.

<ul>
	<li>
	<a href = "release-0.4.html">
	Release notes for 0.4
	</a>

	<li>
	<a href = "release-0.4-contents.html">
	Contents of release 0.4 distribution
	</a>

	<li>
	<a href = "release-0.4-bugs.html">
	Known problems with release 0.4 
	</a>
</ul>

<h3>Release 0.3 (beta)</h3>

This beta distribution of Mercury was released on 18 July 1995.<br>
It was the first public release.

<ul>
	<li>
	<a href = "release-0.3.html">
	Release notes for 0.3
	</a>

	<li>
	<a href = "release-0.3-contents.html">
	Contents of release 0.3 distribution
	</a>

	<li>
	<a href = "release-0.3-bugs.html">
	Known problems with release 0.3
	</a>
</ul>
