<H2>Release of the Day</H2>

When the latest development version of the compiler passes all of its
regression tests a 
<A HREF="ftp://turiel.cs.mu.OZ.AU/pub/mercury/beta-releases/">snapshot</A>
is made available.  The snapshot will contain all the experimental
features announced in the news section.

<p>

Note that this version of the compiler is not as
stable as a full release, so use with caution.
