<h2>Mailing Lists</h2>

There are three Mercury mailing lists.
<ul>
<li>
The mercury-announce list is a very low-volume list used for
announcements about new releases and such-like.
<li>
The mercury-developers list is intended for people actively working on
the Melbourne Mercury compiler.  This list contains diffs of work in
progress and discussions of implementation details of the compiler.
It is <A HREF="mercury-developers/list.html">archived</A>.
<li>
The mercury-users list is intended for general discussion
about Mercury.  It is <A HREF="mercury-users/list.html">
archived</A>.
</ul>
These lists are now managed using the "majordomo" mailing list software.
To subscribe or unsubscribe to either of these mailing lists,
send email with "subscribe" in the body of the mail to
<a href = "mailto:mercury-announce-request@cs.mu.oz.au">
mercury-announce-request@cs.mu.oz.au</a> or
<a href = "mailto:mercury-users-request@cs.mu.oz.au">
mercury-users-request@cs.mu.oz.au</a>
respectively.
Articles for the mercury-users list should be sent
to <a href="mailto:mercury-users@cs.mu.oz.au">mercury-users@cs.mu.oz.au</a>.
