<h2>Mailing Lists</h2>

<h3>Descriptions</h3>

There are five Mercury mailing lists:
<ul>
<li>
<code>mercury-announce</code> is a very low-volume list for announcements
about things directly related to Mercury, e.g. new versions
of the Mercury implementation, tools for Mercury programmers
(such as MCORBA), books about Mercury, etc.

<li>
The <code>mercury-users</code> list is intended for general discussion
about Mercury and related matters of interest to Mercury users.<br>
It is <A HREF="mercury-users/list.html">archived</A> and
<A HREF="search.html">searchable</A>.

<li> The <code>mercury-ads</code> list is intended for advertisments of things
that are not directly related to Mercury but which may be of interest to
Mercury users, e.g. job ads, conference announcements, calls for
papers/participation, and the like.<br>
It is <A HREF="mercury-ads/list.html">archived</A> and
<A HREF="search.html">searchable</A>.

<li>
The <code>mercury-developers</code> list is intended for general discussion
about the development of Mercury and the Mercury implementation and related
matters of interest to the developers of Mercury.<br>
It is <A HREF="mercury-developers/list.html">archived</A> and
<A HREF="search.html">searchable</A>.

<li>
The <code>mercury-reviews</code> list is intended for use by the developers of
Mercury, for the purpose of reviewing changes to the Mercury implementation
(including documentation, test suite, etc.) and the Mercury web site.  This
list is specifically for posting diffs, reviews of diffs, and discussion of
issues raised in such reviews.  It tends to be a fairly high-volume list.<br>
It is <A HREF="mercury-reviews/list.html">archived</A> and
<A HREF="search.html">searchable</A>.
</ul>

<h3>Subscribing and unsubscribing</h3>

These lists are managed using the "majordomo" mailing list software.
To subscribe or unsubscribe to any of these mailing lists,
send email with "subscribe" or "unsubscribe" in the body of the mail
to the corresponding "-request" address:

<ul>
<li> <a href = "mailto:mercury-announce-request@cs.mu.oz.au">
mercury-announce-request@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-users-request@cs.mu.oz.au">
mercury-users-request@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-ads-request@cs.mu.oz.au">
mercury-ads-request@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-developers-request@cs.mu.oz.au">
mercury-developers-request@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-reviews-request@cs.mu.oz.au">
mercury-reviews-request@cs.mu.oz.au</a>
</ul>

<h3>Posting articles</h3>

To submit articles to one of these lists, use the address
without the "-request" part:

<ul>
<li> <a href = "mailto:mercury-users@cs.mu.oz.au">
mercury-users@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-ads@cs.mu.oz.au">
mercury-ads@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-developers@cs.mu.oz.au">
mercury-developers@cs.mu.oz.au</a>
<li> <a href = "mailto:mercury-reviews@cs.mu.oz.au">
mercury-reviews@cs.mu.oz.au</a>
</ul>
