<h2>Mailing Lists</h2>

<h3>Descriptions</h3>

There are five Mercury mailing lists:
<ul>
<li>
<code>announce</code> is a very low-volume list for announcements
about things directly related to Mercury, e.g. new versions
of the Mercury implementation, tools for Mercury programmers
(such as MCORBA), books about Mercury, etc.

<li>
The <code>users</code> list is intended for general discussion
about Mercury and related matters of interest to Mercury users.<br>
It is <A HREF="http://lists.mercurylang.org/pipermail/users/">
archived</A> and searchable.

<li>
The <code>developers</code> list is intended for general discussion
about the development of Mercury and the Mercury implementation and related
matters of interest to the developers of Mercury.<br>
It is <A HREF="http://lists.mercurylang.org/pipermail/developers/">archived</A> and searchable.
Note that in recent times, most the actual development discussion seems to be
done on the <code>reviews</code> list, rather than <code>developers</code> list.
<br>

<li>
The <code>reviews</code> list is intended for use by the developers of
Mercury, for the purpose of reviewing changes to the Mercury implementation
(including documentation, test suite, etc.) and the Mercury web site.  This
list is specifically for posting diffs, reviews of diffs, and discussion of
issues raised in such reviews.  It tends to be a fairly high-volume list.<br>
It is <A HREF="http://lists.mercurylang.org/pipermail/reviews/">archived</A>
and searchable.
</ul>

<h3>Search</h3>

<?php
/*
 * NOTE: When updating the URLs here be sure to also update the URLs in
 * include/search.inc.
 */
?>
<ul>
<li>
<form method="get" action="https://www.google.com/search">
mercury-users:
<input type="text" name="q" size="31" value="" />
<input type="submit" value="Google Search" />
<input type="hidden" name="sitesearch"
	value="lists.mercurylang.org/archives/users"/>
</form>

<li>
<form method="get" action="https://www.google.com/search">
mercury-developers:
<input type="text" name="q" size="31" value="" />
<input type="submit" value="Google Search" />
<input type="hidden" name="sitesearch"
	value="lists.mercurylang.org/archives/developers"/>
</form>

<li>
<form method="get" action="https://www.google.com/search">
mercury-reviews:
<input type="text" name="q" size="31" value="" />
<input type="submit" value="Google Search" />
<input type="hidden" name="sitesearch"
	 value="lists.mercurylang.org/archives/reviews"/>
</form>
</ul>

<h3>Subscribing and unsubscribing</h3>

These lists are managed using the "mailman" mailing list software.
To subscribe or unsubscribe to any of these mailing lists,
send email with "subscribe" or "unsubscribe" in the body of the mail
to the corresponding "-request" address:

<ul>
<li> <a href = "mailto:announce-request@lists.mercurylang.org">
announce-request@lists.mercurylang.org</a>
<li> <a href = "mailto:users-request@lists.mercurylang.org">
users-request@lists.mercurylang.org</a>
<li> <a href = "mailto:developers-request@lists.mercurylang.org">
developers-request@lists.mercurylang.org</a>
<li> <a href = "mailto:reviews-request@lists.mercurylang.org">
reviews-request@lists.mercurylang.org</a>
</ul>

<h3>Posting articles</h3>

To submit articles to one of these lists, use the address
without the "-request" part:

<ul>
<li> <a href = "mailto:users@lists.mercurylang.org">
users@lists.mercurylang.org</a>
<li> <a href = "mailto:developers@lists.mercurylang.org">
developers@lists.mercurylang.org</a>
<li> <a href = "mailto:reviews@lists.mercurylang.org">
reviews@lists.mercurylang.org</a>
</ul>

For more information please see the
<a href="http://lists.mercurylang.org">mailmain list page</a>.

