<h2>Development<span class="submenutitle">/ contributing</span></h2>

<h3>Mercury Libraries and Programs</h3>
<p>
If you've written some code using Mercury we'd love to find out about
it.  If you think it might be in any way useful to other people, you
might be interested in making your code available for download.
That way others can learn from it, use it and improve on it.
</p><p>
We are happy to place it on the Mercury web and ftp sites for you.
Fame and fortune will surely follow.
</p>
<p>
If you would like to contribute a library or program written using
Mercury for others to download and use, here's how you can do it.
</p>
<ul class="indentlist">
<li>
Choose a license for your code that allows other people to
download and use it (by default, copyright law says that nobody
but the author can copy or distribute modified copies).
Something that meets the open source definition would be good
(see <a href="http://www.opensource.org">www.opensource.org</a>).
A pre-written license is always much easier to get right than rolling
your own.  The LGPL and GPL licenses are pretty compatible with the rest
of the Mercury distribution.  The Artistic, and BSD-like (without
advertising clause) licenses are also pretty popular.
</li>
<li>
Apply this license to your code (e.g. make sure your source
files and README file clearly state your name/employer and where to find
the licensing conditions and include a file with the conditions).  A
contact email address is also a good thing to include here.
</li>
<li>
Make your software available online
somewhere.  If possible try to include a version number in your
tar or zip file (e.g. mylibrary-0.4.zip or myprogram-1.2.1.tar.gz).
If you can't do this, attach it in email in the next step.
</li>
<li>
Email <a href="mailto:reviews@lists.mercurylang.org">reviews@lists.mercurylang.org</a>.
and let us know that it's available (or it is attached), what it is,
and give us the URL.  We'll check it out and if all is well will add it
to the archive.
</li>
</ul>


<h3>Modifications to the Mercury System</h3>
<p>
If you've modified something in the Mercury system and would like it to
become part of the main distribution, we'd be very interested in your
work.
</p>
<p>
The developers mailing list is intended for discussing proposed
changes to the Mercury system.  If you would like to contribute reasonably
frequently it might be a good idea to subscribe, or at least browse the
archives of this list, simply to get an idea of the kinds of standards
required for integrating code into the main distribution.
</p>
<p>
Rather than listing many authors in the header of each source file it is
better to refer to all the authors as a group.
Therefore in the header of each source file the copyright is assigned to
"The Mercury Team" (since 2013), and list the authors individually on the
<a href="people.html">authors page</a>.
</p>
<p>
Note that if you contribute to Mercury as part of your occupation your
employer may own the copyright on your work.
In these cases you should talk with your employer about contributing to
Mercury.
We list organisations that have contributed to Mercury on the
<a href="people.html">authors page</a>.
</p>


