<h2>Development<span class="submenutitle">/ contributing</span></h2>

<h3>Mercury Libraries and Programs</h3>

<p>Volker Wysk is maintaining
<a href="https://volker-wysk.de/mercury/resources.html">
a list of Mercury resources</a>.
</p>

<p>
Previously, we accepted Mercury libraries in the "extras" repository.
This was more useful when code hosting was harder to come by,
and we could keep code up-to-date with language changes.
</p>

<p>
These days, if you have some code to share,
we suggest you use one of the free code hosting services.
Feel free to tell everyone about it on the
<a href="../contact.html">Mercury users mailing list</a>.
</li>

<h3>Modifications to the Mercury System</h3>
<p>
If you've modified something in the Mercury system and would like it to
become part of the main distribution, we'd be very interested in your
work.
</p>
<p>
The developers mailing list is intended for discussing proposed
changes to the Mercury system.  If you would like to contribute reasonably
frequently it might be a good idea to subscribe, or at least browse the
archives of this list, simply to get an idea of the kinds of standards
required for integrating code into the main distribution.
</p>
<p>
Rather than listing many authors in the header of each source file it is
better to refer to all the authors as a group.
Therefore in the header of each source file the copyright is assigned to
"The Mercury Team" (since 2013), and list the authors individually on the
<a href="people.html">authors page</a>.
</p>
<p>
Note that if you contribute to Mercury as part of your occupation your
employer may own the copyright on your work.
In these cases you should talk with your employer about contributing to
Mercury.
We list organisations that have contributed to Mercury on the
<a href="people.html">authors page</a>.
</p>


