<H2>Development<span class="submenutitle">/ contributing</span></H2>

<H3>Developer Documentation</H3>
<p>
There is some developer documentation at the Mercury
<a href="<?php echo $root ?>/development/developer.html">developer information page</a>.
</p>

<H3>Mercury Libraries and Programs</H3>
<p>
If you've written some code using Mercury we'd love to find out about
it.  If you think it might be in any way useful to other people, you
might be interested in making your code available for download.
That way others can learn from it, use it and improve on it. 
</p><p>
We are happy to place it on the Mercury web and ftp sites for you.
Fame and fortune will surely follow.
</p>
<p>
If you would like to contribute a library or program written using
Mercury for others to download and use, here's how you can do it.
</p>
<UL class="indentlist">
<LI>
Choose a license for your code that allows other people to
download and use it (by default, copyright law says that nobody
but the author can copy or distribute modified copies).
Something that meets the open source definition would be good
(see <a href="http://www.opensource.org">www.opensource.org</a>).
A pre-written license is always much easier to get right than rolling
your own.  The LGPL and GPL licenses are pretty compatible with the rest
of the Mercury distribution.  The Artistic, BSD-like (without
advertising clause) and plain old public domain (e.g. no copyright at
all) are also pretty popular.
</li>
<LI>
Apply this license to your code (e.g. make sure your source
files and README file clearly state your name/employer and where to find
the licensing conditions and include a file with the conditions).  A
contact email address is also a good thing to include here.
</li>
<LI>
Make your software available on an ftp or http site
somewhere.  If possible try to include a version number in your
tar or zip file (e.g. mylibrary-0.4.zip or myprogram-1.2.1.tar.gz).
If you can't do this, attach it in email in the next step.
</li>
<LI>
Email <a href="mailto:mercury@cs.mu.oz.au">mercury@cs.mu.oz.au</a>.
and let us know that it's available (or it is attached), what it is,
and give us the URL.  We'll check it out and if all is well will add it
to the archive.
</li>
</UL>


<H3>Modifications to the Mercury System</H3>
<p>
If you've modified something in the Mercury system and would like it to
become part of the main distribution, we'd be very interested in your
work.
</p>
<p>
The mercury-developers mailing list is intended for discussing proposed 
changes to the Mercury system.  If you would like to contribute reasonably
frequently it might be a good idea to subscribe, or at least browse the
archives of this list, simply to get an idea of the kinds of standards
required for integrating code into the main distribution.
You can also email <a href="mailto:mercury@cs.mu.oz.au">mercury@cs.mu.oz.au</a>
and discuss it with the Mercury team.
</p>
<p>
There is an issue with copyright ownership in the Mercury system. 
We'd like to retain the freedom to modify the license of the
Mercury system in future releases (in particular, we may decide to
dual-license the Mercury system so as to make it compatible with other
open source licenses out there).  Doing this with hundreds of copyright
holders is practically impossible, since you need the agreement of every
single one of them to make changes.
</p>
<p>
Under the current license you are free to make any modifications
you like and distribute them.  However we ask that if you want your
modifications to be merged back into the main line of development, you
talk to us about this issue.  The easiest solution is to place your
changes into the public domain (e.g. give up copyright ownership on
them) and then we can merge them into the main compiler.  This is a nice
simple mechanism for getting around the hundreds of authors problem.
If you have an employer who has some control over your copyright, we
have some standard documents for doing this kind of thing.  It is almost
always preferable to ask an employer to sign a form than to try to explain
the concept (possibly confusing or scaring them in the process).  Please 
email <a href="mailto:mercury@cs.mu.oz.au">mercury@cs.mu.oz.au</a> if
you want to discuss contributing changes to the Mercury system.
</p>


