<h2>Development<span class="submenutitle">/ developer documentation</span></h2>

<p>
These pages may contain out-of-date information.
We hope to update or replace this information in the future.
</p>

<?php

/*
Note that this information is not stored in this repository.  It is stored
in compiler/notes/*.html.  On the webserver we maintain a checkout of the
main source repository as well as the www repository and configure apache to
look in the main source repository to find these documents.
*/

?>

<div class="developer">
<ul class="nonindentlist">
<li> 	
<h3><a href="developers/developer_intro.html">Developer Introduction</a></h3>
	<p>
	Tips and tricks for developers just starting to work with
	the Mercury source code.
	<p>
	</li>

<li> 	
<h3><a href="developers/c_coding_standard.html">C Coding Standard For The Mercury Project</a></h3>
	<p>The standard used for the C source in the Mercury compiler. </p>
</li>

<li>	
<h3><a href="developers/reviews.html">Reviews</a></h3>
	<p>Outlines reviewing procedure. </p>
</li>

<li>	
<h3><a href="developers/coding_standards.html">Mercury Coding Standards</a> </h3>
	<p>Standard for Mercury code. </p>
</li>

<li>	
<h3><a href="developers/compiler_design.html">Compiler Design</a> </h3>
	<p>Details of the compiler design. </p>
</li>

<li>	
<h3><a href="developers/allocation.html">Allocation</a> </h3>
<p>	Details of the allocation scheme currently being implemented. </p>
</li>

<li>	<h3><a href="developers/release_checklist.html">Release checklist</a> </h3>
	<p>The release procedure. </p>

<li>	<h3><a href="developers/gc_and_c_code.html">Garbage collection and C code</a> </h3>
</li>	
<br/><br/>
<li>	
<h3>
<a href="developers/glossary.html">Glossary</a> </h3>
	<p>Terms used in the Mercury implementation.  </p>
</li>

<li>	
<h3><a href="developers/todo.html">To do list</a> </h3>
	<p>Things still to do in the Mercury project.  </p>

</li>

<li>
<h3><a href="developers/work_in_progress.html">Work in progress</a> </h3>
<p>Things currently being done on the Mercury project.  </p>
</li>

<li>	
<h3><a href="developers/bootstrapping.html">Bootstrapping</a> </h3>
	<p>What to do when a change requires bootstrapping. </p>
</li>

<!---------
%% Take this out of comments when the bytecode docs have settled down a bit.
<li>	<strong>Bytecode</strong> <br>
	Information on the Mercury bytecode.  <p>

	Available in
	<a href="developers/bytecode.html">HTML</a>
	<p>
-------->

</ul>
<p>

</div>
