<h2>Development<span class="submenutitle">/ the team</span></h2>
<p>
People who are currently working on the Mercury project
at the University of Melbourne:
</p>
<ul class="nonindentlist">
<li> Paul Bone, pbone at csse.unimelb.edu.au, Phd student</li>
<li> Mark Brown, mark at csse.unimelb.edu.au, research engineer (NICTA)</li>
<li> Julien Fischer, juliensf at csse.unimelb.edu.au, research engineer (NICTA)</li>
<li> Ian MacLarty, maclarty at csse.unimelb.edu.au, software engineer (Mission Critical IT)</li>
<li> <a href = "http://www.cs.mu.OZ.AU/~lee/">Lee Naish</a>,
lee at cs.mu.OZ.AU, senior lecturer</li>
<li> <a href = "http://www.cs.mu.OZ.AU/~schachte/">Peter Schachte</a>,
schachte at cs.mu.OZ.AU, lecturer</li>
<li> <a href = "http://www.cs.mu.OZ.AU/~zs/">Zoltan Somogyi</a>,
zs at cs.mu.OZ.AU, senior lecturer</li>
<li> <a href = "http://www.cs.mu.OZ.AU/~harald/">Harald S&oslash;ndergaard</a>,
harald at cs.mu.OZ.AU, senior lecturer</li>
<li> Peter Wang, software engineer (Mission Critical IT)</li>

</ul>

<p>
People who have worked on the project in the past,
some of whom are still informally associated with the project:
</p>

<div style="float: left; width: 360px; margin: -10px 60px -45px 0px;">
<ul class="nonindentlist">
<li> Ralph Becket, research fellow </li>
<li> Tibor Benyi, honours student</li>
<li> James Bligh, directed studies student</li>
<li> Thomas Conway, PhD student</li>
<li> Michael Day, summer student</li>
<li> Tyson Dowd, PhD student</li>
<li> Andrew Ebert, summer student</li>
<li> Paul Incani, summer student</li>
<li> David Jeffery, PhD student</li>
<li> Julian Grady, summer student</li>
<li> Andrew Bromage, MSc student</li>
<li> Levi Cameron, summer student</li>
<li> Ina Cheng, summer student</li>
<li> Waye-Ian Chiew, summer student</li>
<li> Richard Fothergill, summer student</li>
<li> Warwick Harvey, research fellow at Monash University</li>
<li> Fergus Henderson, research fellow</li>
<li> Fransiska Handoko, summer student</li>
<li> Oliver Hutchinson, summer student</li>
<li> Robert Hutton, summer student</li>
<li> Erwan Jahier, jahier at imag.fr, research assistant at Verimag in Grenoble, France</li>
<li> Darko Jankovic, summer student</li>
</ul>
</div>

<div style="float: left; width: 360px;margin-top: -10px;">
<ul class="nonindentlist">
<li> Robert Jeschofnik, directed studies student</li>
<li> Charles Kemp, summer student</li>
<li> Jane Langley, summer student</li>
<li> Peter Malkin, summer student</li>
<li> Simon Mei, summer student</li>
<li> Ben Mellor, honours student</li>
<li> Leon Mika, honours student</li>
<li> David Overton, PhD student</li>
<li> Bill Peden, honours student</li>
<li> Quan Phan, Phd student, Catholic University of Leuven</li>
<li> Adrian Pellas-Rice, summer student</li>
<li> Peter Ross, MEngSc student</li>
<li> Steven Siew, honours student</li>
<li> Chris Speirs, summer student</li>
<li> Simon Taylor, research assistant</li>
<li> Vanessa Teague, summer student</li>
<li> Bert Thompson, research assistant</li>
<li> Sam Thurairatnam, summer student</li>
<li> Nicolas Watmough, summer student</li>
<li> Geoff Wilson, summer student</li>
<li> Michael Wybrow, summer student</li>
<li> Lars Yencken, summer student</li>
</ul>

</div>

