<h2>Development<span class="submenutitle">/ the team</span></h2>
<p>
People who are currently working on the Mercury project:
</p>
<ul class="nonindentlist">
<li> Paul Bone, paul at mercurylang.org, PhD, (Mission Critical IT)</li>
<li> Julien Fischer, juliensf at mercurylang.org, (Opturion)</li>
<li> Ian MacLarty, ian at mercurylang.org, MSc, (Opturion)</li>
<li> <a href = "http://www.cs.mu.OZ.AU/~zs/">Zoltan Somogyi</a>,
zs at mercurylang.org, PhD</li>
<li> Peter Wang, (YesLogic)</li>
</ul>

<p>
People who have worked on the project in the past,
some of whom are still informally associated with the project:
</p>

<div style="float: left; width: 360px; margin: -10px 60px -45px 0px;">
<ul class="nonindentlist">
<li> Ralph Becket, research fellow</li>
<li> Mark Brown, research engineer</li>
<li> Tibor Benyi, honours student</li>
<li> James Bligh, directed studies student</li>
<li> Thomas Conway, PhD student</li>
<li> Michael Day, summer student (YesLogic)</li>
<li> Tyson Dowd, PhD student</li>
<li> Andrew Ebert, summer student</li>
<li> Paul Incani, summer student</li>
<li> David Jeffery, PhD student</li>
<li> Julian Grady, summer student</li>
<li> Andrew Bromage, MSc student</li>
<li> Levi Cameron, summer student</li>
<li> Ina Cheng, summer student</li>
<li> Waye-Ian Chiew, summer student</li>
<li> Richard Fothergill, summer student</li>
<li> Warwick Harvey, research fellow (Monash University)</li>
<li> Fergus Henderson, research fellow</li>
<li> Fransiska Handoko, summer student</li>
<li> Oliver Hutchinson, summer student</li>
<li> Robert Hutton, summer student</li>
<li> Erwan Jahier, jahier at imag.fr,
research assistant (Verimag in Grenoble, France)</li>
<li> Darko Jankovic, summer student</li>
<li> Robert Jeschofnik, directed studies student</li>
</ul>
</div>

<div style="float: left; width: 360px;margin-top: -10px;">
<ul class="nonindentlist">
<li> Charles Kemp, summer student</li>
<li> Jane Langley, summer student</li>
<li> Peter Malkin, summer student</li>
<li> Simon Mei, summer student</li>
<li> Ben Mellor, honours student</li>
<li> Leon Mika, honours student</li>
<li> Lee Naish, senior lecturer</li>
<li> David Overton, PhD student</li>
<li> Bill Peden, honours student</li>
<li> Quan Phan, PhD student, (Catholic University of Leuven)</li>
<li> Adrian Pellas-Rice, summer student</li>
<li> Peter Ross, MEngSc student</li>
<li> Peter Schachte, lecturer</li>
<li> Harald S&oslash;ndergaard, senior lecturer</li>
<li> Steven Siew, honours student</li>
<li> Chris Speirs, summer student</li>
<li> Simon Taylor, research assistant</li>
<li> Vanessa Teague, summer student</li>
<li> Bert Thompson, research assistant</li>
<li> Sam Thurairatnam, summer student</li>
<li> Nicolas Watmough, summer student</li>
<li> Geoff Wilson, summer student</li>
<li> Michael Wybrow, summer student</li>
<li> Lars Yencken, summer student</li>
</ul>

</div>

