<h2>About Mercury<span class="submenutitle">/ related </span></h2>

<h3>Projects using Mercury</h3>

<ul class="nonindentlist">
<li>The <a href="http://www.g12.csse.unimelb.edu.au/">G12 Constraint Programming Platform</a></li>
<li>The <a href="http://www.csse.monash.edu.au/~mbanda/hal/index.html">HAL Project</a></li>
<li>The Aditi Project</li>
<li> <a href="http://www.winikoff.net/pipe/index.html">Animating Z specifications using Mercury</a></li>
<li> <a href="http://svrc.it.uq.edu.au/Possum/">Possum</a>, an animator for Z
specifications with a Tk GUI</li>
<li> The <a href="http://www.missioncriticalit.com/odase.html">ODASE</a>
	platform, a suite of tools written in Mercury for developing business
	applications using ontologies.  The platform has been used to deliver a
	number of commercial projects.</li>
<li> The <a href="http://www.princexml.com">Prince XML and HTML formatter.</a>
	Prince takes HTML or XML and produces PDF formatted according to 
	user-supplied CSS rules.</li>
</ul>

<p>
If you are using Mercury in your project, please contact us!
</p>
<br/>
<h3>Other Related Languages</h3>

<ul class="nonindentlist">
<li>
<a href = "http://www.scs.leeds.ac.uk/hill/GOEDEL/expgoedel.html">Goedel</a>
 is a logic programming language, with a strong type system,
module system, and support for infinite precision numerical calculation
and meta-programming facilities.
</li>
<li>
<a href = "http://sisal.sourceforge.net/">Sisal</a> is a high-performance portable parallel functional programming language.
</li>
<li>
<a href = "http://www.cs.kun.nl/~clean">Clean</a> is a general purpose, higher order, pure and lazy functional
programming language. It uses uniqueness types which are similar to
Mercury's unique modes, and allows programmers to build distributed
systems.
</li>
</ul>
