<h2>Documentation</h2>
<p>
This page contains documentation for Mercury version
14.01.1,
<?php /* <a href=<?php echo $root ?>/download/release.html>11.07.1</a>, */ ?>
and for the latest
<?php /* <a href=<?php echo $root ?>/download/rotd.html> */ ?>
development snapshot.
<?php /* /a>.*/ ?>
</p>

<p>
The HTML versions are set up for browsing, however, if you'd prefer a
copy of the entire document, links to PDF are provided.
</p>

<ul class="nonindentlist2">
	<li> 
	<h3>Ralph Becket Mercury tutorial</h3>
	An introduction to Mercury.
	This is still under development. 
	Feedback would be greatly appreciated.
	<table class="documentation">
	<tr><td>
	<a href="papers/book.pdf"><button class="button">PDF</button></a>
	</td></tr>
	</table>
	</li>



	<li> 
	<h3>Mercury Language Reference Manual</h3>
	Information on the Mercury programming language
	itself, including syntax, types and modes, determinism, 
	the module system, foreign language interface and higher-order
	programming.

	<table class="documentation">
	<tr>
	<td>Current Release</td>
	<td><a href="<?php echo $ref_man_release ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $release_doc_dir ?>/reference_manual.pdf"><button class="button">PDF</button></a></td>
	</tr>
	<tr>
	<td>Rotd (snapshot)</td>
	<td><a href="<?php echo $ref_man_latest ?>"><button class="button">HTML</button></a>
	<td><a href="<?php echo $latest_doc_dir ?>/reference_manual.pdf"><button class="button">PDF</button></a>
	</tr>
	</table>
	</li>

	<li> 
	<h3>Mercury User's Guide</strong></h3>
	Information on the Mercury compiler, including
	how to compile, using multiple modules, profiling, debugging,
	and compilation options.

	<table class="documentation">
	<tr>
	<td>Current Release</td>
	<td><a href="<?php echo $user_guide_release ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $release_doc_dir ?>/user_guide.pdf"><button class="button">PDF</button></a></td>
	</tr>
	<tr>
	<td>Rotd (snapshot) </td>
	<td><a href="<?php echo $user_guide_latest ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $latest_doc_dir ?>/user_guide.pdf"><button class="button">PDF</button></a></td>
	</tr>
	</table>
	</li>
	
	<li>
	<h3>Mercury Library Reference Manual</h3>
	Descriptions of the interfaces to the library
	which comes with the Mercury distribution.

	<table class="documentation">
	<tr>
	<td>Current Release <td>
	<td><a href="<?php echo $library_man_release ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $release_doc_dir ?>/library.pdf"><button class="button">PDF</button></a></td>
	</tr>
	<tr>
	<td>Rotd (snapshot)<td>
	<td><a href="<?php echo $library_man_latest ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $latest_doc_dir ?>/library.pdf"><button class="button">PDF</button></a></td>
	<tr>
	</table>
	</li>
	
	<li> 
	<h3>Prolog to Mercury Transition Guide</h3>
	Information to assist programmers to move Prolog
	programs to Mercury. Includes information on differences in
	the languages and common programming styles.

	<table class="documentation">
	<tr>
	<td>Current Release</td>
	<td><a href="<?php echo $trans_guide_release ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $release_doc_dir ?>/transition_guide.pdf"><button class="button">PDF</button></a></td>
	</tr>
	<tr>
	<td>Rotd (snapshot)</td>
	<td><a href="<?php echo $trans_guide_latest ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $latest_doc_dir ?>/transition_guide.pdf"><button class="button">PDF</button></a></td>
	</tr>
	</table>
	</li>

	<li> 
	<h3>Comparing Mercury and Haskell</h3>
	A point-by-point comparison of some of the differences
	between Mercury and Haskell 98, in particular with
	regard to their type systems.
	
	<table class="documentation">
	<tr>
	<td><a href="../about/comparison_with_haskell.html"><button class="button">HTML</button></a></td>
	</tr>
	</table>
	</li>

	<li> 
	<h3>Frequently Asked Questions</h3>
	Information on common programming errors, problems caused by
	unimplemented Mercury features and where to turn for help.<p>
	
	<table class="documentation" style="width: 250px;">
	<tr>
	<td><a href="<?php echo $faq_release ?>"><button class="button">HTML</button></a></td>
	<td><a href="<?php echo $release_doc_dir ?>/faq.pdf"><button class="button">PDF</button></a></td>
	</tr>
	</table>
	</li>
</ul>
