<h2>Documentation<span class="submenutitle">/ learning </span></h2>

<p>This page contains links to resources for learning and understanding Mercury.</p>

<ul class="nonindentlist2">
        <li>
        <h3>Mercury crash course</h3>
        <a href="https://mercury-in.space/crash.html">
	An introduction to Mercury through worked examples.
        </a>
        </li>

	<li>
	<h3>Ralph Becket Mercury tutorial</h3>
	An introduction to Mercury.
	This is still under development.
	Feedback would be greatly appreciated.
	<table class="documentation">
	<tr><td>
	<a href="papers/book.pdf"><button class="button">PDF</button></a>
	</td></tr>
	</table>
	</li>

        <li>
        <h3>Mercury wiki tutorial</h3>
        <a href="https://github.com/Mercury-Language/mercury/wiki/Tutorial">
        Another introduction to Mercury.
        </a>
        </li>
</ul>
