<H2>Projects using Mercury</H2>

If you are using Mercury in your project, please contact us at
<a href="mailto:mercury@csse.unimelb.edu.au">mercury@csse.unimelb.edu.au</a>.

<UL>
<LI> <A HREF="http://g12.research.nicta.com.au/">The G12 Constraint Programming Platform</A>
<LI> <A HREF="http://www.csse.monash.edu.au/~mbanda/hal/index.html">The
	HAL Project</A>
<LI> <A HREF="http://www.cs.mu.oz.au/aditi">The Aditi Project</A>
<LI> <A HREF="http://www.winikoff.net/pipe/index.html">Animating Z
        specifications using Mercury</A>
<LI> <A HREF="http://svrc.it.uq.edu.au/Possum/">Possum, an animator for Z
specifications with a Tk GUI</A>
<LI> The <A HREF="http://www.missioncriticalit.com/odase.html">ODASE</A>
	platform, a suite of tools writen in Mercury for developing business
	applications using ontologies.  The platform has been used to deliver a
	number of commercial projects.
</UL>
