<H2>Projects using Mercury</H2>

If you are using Mercury in your project, please contact us at
<a href="mailto:mercury@cs.mu.oz.au">mercury@cs.mu.oz.au</a>.

<UL>
<LI> <A HREF="http://www.csse.monash.edu.au/~mbanda/hal/index.html">The
	HAL Project</A>
<LI> <A HREF="http://www.cs.mu.oz.au/aditi">The Aditi Project</A>
<LI> <A HREF="http://www.winikoff.net/pipe/index.html">Animating Z
        specifications using Mercury</A>
<LI> <A HREF="http://svrc.it.uq.edu.au/Possum/">Possum, an animator for Z
specifications with a Tk GUI</A>
</UL>
