<h3> Keeping in contact </h3>

If you have any comments, suggestions, bug reports, or issues you would
like to discuss regarding Mercury, feel free to contact us. Provided
here is general Mercury group contact information, information
on people involved in Mercury, and instructions on how to subscribe to
the Mercury announcements and users mailing lists.

<ul>
        <li>
        <a href = "contact/email.html">
        Mercury email addresses</a>

        <li>
        <a href = "contact/people.html">
        People involved in the Mercury project</a>

        <li>
        <a href = "mailing-lists/mailing-lists.html"> 
        Information on the Mercury mailing lists</a>.
</ul>
