<h2>Contact</h2>

<p>
If you have any questions, comments, suggestions, bug reports, or issues you would
like to discuss regarding Mercury, feel free to contact us on one of the
following mailing lists.
</p>

<p>
Bug reports may also be added to the
<a href="https://bugs.mercurylang.org/">bug tracker</a>.
If sending a bug report, please enclose as much information as possible,
including, if possible source code (such as a small test case that exhibits the
bug), any error messages encountered, operating system version, and
configuration information, compiler flags used and Mercury compiler version.
Also, you might want to check the current release to see if a newer release is
available, or see the bug tracker to see if the bug has already been reported.
</p>

<p>
If you wish to contact the core team about something not suitable for the
mailing lists then e-mail
<a href="mailto:mercury@mercurylang.org">mercury@mercurylang.org</a>
User support questions are best handled on the mercury-users mailing list.
</p>

<h3>Mailing Lists</h3>

<p>
There are four Mercury
<a href="http://lists.mercurylang.org/">mailing lists</a>:
</p>

<ul class="nonindentlist">
<li>
<a href="http://lists.mercurylang.org/listinfo/announce"><span class="mailinglistname">mercury-announce</span></a>
is a very low-volume list for announcements about things directly related to
Mercury, e.g. new versions of the Mercury implementation, tools for Mercury
programmers, books about Mercury, etc.
</li>

<li>
The
<a href="http://lists.mercurylang.org/listinfo/users"><span class="mailinglistname">mercury-users</span></a>
list is intended for general discussion about Mercury and related matters of
interest to Mercury users.
<br/>
It is <a href="http://lists.mercurylang.org/pipermail/users/">archived</a> and searchable.
</li>

<li>
The
<a href="http://lists.mercurylang.org/listinfo/developers"><span class="mailinglistname">mercury-developers</span></a>
list is intended for general discussion about the development of Mercury and
the Mercury implementation and related matters of interest to the developers of
Mercury.
<br/>
It is
<a href="http://lists.mercurylang.org/pipermail/developers/">archived</a>
and searchable. Note that in recent times, most the actual development
discussion seems to be done on the mercury-reviews list, rather than
mercury-developers.
</li>

<li>
The
<a href="http://lists.mercurylang.org/listinfo/reviews"><span class="mailinglistname">mercury-reviews</span></a>
list is intended for use by the developers of Mercury, for the purpose of
reviewing changes to the Mercury implementation (including documentation, test
suite, etc.) and the Mercury web site. This list is specifically for posting
diffs, reviews of diffs, and discussion of issues raised in such reviews. It
tends to be a fairly high-volume list.
<br/>
It is
<a href="http://lists.mercurylang.org/pipermail/reviews/">archived</a>
and searchable.
</li>
</ul>

<p>
To subscribe or unsubscribe to any of these mailing lists, please use the forms
on the respective pages.
</p>

<p>
To post to one of these lists, send an e-mail to one of the following addresses:
</p>

<ul class="nonindentlist">
<li><a href="mailto:users@lists.mercurylang.org">users@lists.mercurylang.org</a></li>
<li><a href="mailto:developers@lists.mercurylang.org">developers@lists.mercurylang.org</a></li>
<li><a href="mailto:reviews@lists.mercurylang.org">reviews@lists.mercurylang.org</a></li>
</ul>

<h3>Search the Archives</h3>

<p>
Please use the search bar below to search the archives:
</p>

<form class="searchbar" method="get" action="http://www.google.com/search">
<table border="0" cellpadding="0">
<tr>
<td>
<input class="textbox" type="text"   name="q" size="25" maxlength="255" value="" />
<input class="submit" type="submit" value="Search" />
</td>
</tr>
<tr>
<td>
<input type="hidden"  name="sitesearch" value="mercurylang.org/mailing-lists"/>
</td>
</tr>
</table>
</form>
