<h2>Development</h2>

<h3>Source code repository</h3>

<p>
The Mercury source code is hosted at
<a href="https://github.com/Mercury-Language">GitHub</a>.
You can check out the latest copy of the source code using a git client,
for example using this command:
</p>
<p>
<code>
git clone https://github.com/Mercury-Language/mercury.git
</code>
</p>

<h3>IDE and editor support</h3>

<ul>
<li>
    Support for Vim is provided by the Mercury developers.
    See the <code>vim</code> directory of any release package.
</li>
<li>
    <a href="https://github.com/flycheck/flycheck-mercury">Flycheck library</a>
    for Emacs
</li>
<li>
    A <a href="http://kai.mercury.mind-era.com/">plugin</a> is available for
    the Eclipse IDE.
</li>
<li>
    A <a href="http://opcode.cc/projects_mercury_ide.en.html">plugin</a>
    is available for the NetBeans IDE.
</li>
</ul>

<h3>Mailing lists</h3>

<p>
Discussion about Mercury happens on the mailing lists.
You can find them on the <a href="contact.html">Contact</a> page.
</p>

<h3>Reporting bugs</h3>

<p>
Bugs may be reported on our bug tracker,
or on the mercury-users mailing list.
</p>
