<h3> How to get Mercury </h3>

The Mercury compiler is free software, and is distributed under the
terms
of the GNU General Public License. Binary distributions are available
for several popular platforms, and a full source distribution is also 
available. Included in the distribution is an extensive library,
documentation, and programming environment support tools.

<ul>
        <li>
        <a href = "download/release.html">
        The current release of the Mercury system</a>

        <li>
        <a href = "download/rotd.html">
        The current snapshot for the Mercury system</a>

        <li>
        <a href = "download/old-release.html">
        Old releases of the Mercury system</a>
</ul>

If you are using Debian GNU/Linux on an x86 processor, the previous
release of Mercury, namely Mercury 0.6.2, is available
as a Debian package as part of Debian 1.3.  Thanks to Milan Zamazal
(pdm@fi.muni.cz) for preparing this package.  You can download it from
any of the Debian mirrors - see the <a
href="http://www.debian.org">Debian
Web Site</a> for more information on Debian.  Some technical information
on this package is available with the <a href="download/old-release.html">
old releases</a> information. 
If you have a libc6 based system, Mercury 0.7.3 is now available as a
Debian package.
