<h2>MERCURY Programming Language</h2>
<h3> What is Mercury? </h3>
<p>
Mercury is a new logic/functional programming language, which combines
the clarity and expressiveness of declarative programming with advanced
static analysis and error detection features. Its highly optimized
execution algorithm delivers efficiency far in excess of existing logic
programming systems, and close to conventional programming systems.
Mercury addresses the problems of large-scale program development,
allowing modularity, separate compilation, and numerous
optimization/time trade-offs.
</p>
<p>
Logic programming languages have been around for more than twenty years.
Despite the expected advantages of a very high level programming
language based upon well developed theories of logic over conventional
programming languages (such as C, C++, Pascal and Ada).
</p> 


<h3>Latest News</h3>

<ul class="nonindentlist2" id="newslist">
<?php
    include "$root/include/latest_news.inc";
?>
</ul>

<p>

This list contains only the latest news items.<br>
For older news items, see the
(<a href="<?php echo $root ?>/news.html">complete news archive</a>).

<p>

News is also available as an RSS feed at
<a href="<?php echo $root; ?>/rss.xml">http://www.mercury.csse.unimelb.edu.au/rss.xml</a>.
