<h2></h2>
<div class="banner"></div>

<p style="font-weight: bold; font-family: georgia; font-size: 19px; line-height:1.2em">
Mercury is a new logic/functional programming language, which combines
the clarity and expressiveness of declarative programming with advanced
static analysis and error detection features. 
</p>
<p>
Its highly optimized
execution algorithm delivers efficiency far in excess of existing logic
programming systems, and close to conventional programming systems.
Mercury addresses the problems of large-scale program development,
allowing modularity, separate compilation, and numerous
optimization/time trade-offs.
</p>

<hr style="color: white;margin: 30px 0px 30px 0px;"/>

<div class="quote" style="line-height: 2.2em;max-width: 400px; min-width: 250px;float: right; margin: 0px 10px 20px 20px; border: 1px solid white;" align="left">
<h2 style="font-size: 24px;color: #06437b; font-style: italic;">
&ldquo;Mercury is free software,<br/> and is distributed under the terms of the GNU General Public License. 
</h2>
</div>

<h3>Latest News</h3>

<ul class="nonindentlist2" id="newslist" style="">
<?php
    include "$root/include/latest_news.inc";
?>
</ul>

<p>
This list contains only the latest news items.<br>
For older news items, see the
(<a href="<?php echo $root ?>/news.html">complete news archive</a>).
</p>
<p>
News is also available as an RSS feed at
<a href="<?php echo $root; ?>/rss.xml">http://www.mercury.csse.unimelb.edu.au/rss.xml</a>.
</p>
