<?
    include "$root/include/whatis.inc";
?>
<h3>Latest News</h3>

<table>
<?
    include "$root/include/latest_news.inc";
?>
</table>

<p>

This list contains only the latest news items.<br>
For older news items, see the
(<a href="<? echo $root ?>/news.html">complete news archive</a>).

<p>

News is also available as an RSS feed at
<a href="<? echo $root; ?>/rss.xml">http://www.mercury.csse.unimelb.edu.au/rss.xml</a>.
