<h3> Why use Mercury? </h3>

You may be interested in a more detailed examination of our motivation
in creating Mercury, the features of the Mercury language, or
the benchmark results and benchmarks we have used to evaluate its
performance.
<ul>
        <li>
        <a href = "information/motivation.html">
        Motivation and overview</a>

        <li>
        <a href = "information/features.html">
        The main features of Mercury</a>

        <li>
        <a href = "information/benchmarks.html">
        Benchmarking information</a>
</ul>

<!-- This link doens't work anymore.
However, you don't need to take our word for it. Chris Phelps, a student
at UMBC created an independent 
<a href = "http://www.cs.umbc.edu/~cphelp1/mercury.html"> 
case study</a> 
of Mercury 0.4.  ``Mercury has definite potential to be one of the hot
languages in the next few years.''
-->

<h3> Information on Mercury </h3>

The Mercury distribution comes with extensive documentation, and various
academic papers have been written about the new language features and
innovative implementation techniques of the Mercury compiler. In
addition,
we've compiled a short list of projects with similar aims to the Mercury
project.

<ul>
        <li>
        <a href = "information/documentation.html">
        Documentation on Mercury</a>

        <li>
        <a href = "information/papers.html">
        Papers and presentations on Mercury</a>

        <li>
        <a href = "information/deep_demo.html">
        An overview and demo of the Mercury deep profiler</a>

        <li>
        <a href = "information/related.html">
        Related projects</a>

        <li>
        <a href = "information/developer.html">
        Information for the developers of Mercury</a>
</ul>

<h3> Events and Reports </h3>

Want to know more about what's happening with Mercury?
<p>
Check out our <a href = "information/events.html">Events</a>
and <a href = "information/reports.html">Reports</a> web pages.

