<ul class="menu">
<a href="<?php echo $root?>/about.html"><li>About</li></a>
	<ul class="submenu">
	<li><a href="<?php echo $root?>/information/motivation.html">overview</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/information/features.html">features</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/information/benchmarks.html">benchmarks</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/backends.html">back ends</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/information/related.html">related</a></li>
	</ul>
<a href="<?php echo $root?>/news.html"><li>News</li></a>
<a href="<?php echo $root?>/download.html"><li>Download</li></a>
	<ul class="submenu">
	<li><a href="">license</a></li>
	<hr/>
	<li><a href="">releases</a></li>
	<hr/>
	<li><a href="">release of the day(snapshot)</a></li>
	<hr/>
	<li><a href="">beta releases</a></li>
	</ul>
<a href="<?php echo $root?>/information/documentation.html"><li>Documentation</li></a>
	<ul class="submenu">
	<li><a href="<?php echo $root?>/information/papers.html">papers</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/information/deep_demo.html">deep profiler</a></li>
	</ul>
<a href=""><li>Development</li></a>
	<ul class="submenu">
	<li><a href="<?php echo $root?>/information/developer.html">developers documentation</a></li>
	<hr/>
	<li><a href="http://bugs.mercury.csse.unimelb.edu.au">bugs database</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/contact/people.html">the team</a></li>
	<hr/>
	<li><a href="<?php echo $root?>/contributions.html">contributing</a></li>
	</ul>
<a href="<?php echo $root?>/contact.html"><li>Contact</li></a>
</ul>