[Feb 1 1998] Mercury 0.7.3 has been ported to glibc for debian.<BR>
[Nov 1 1997] <A HREF="download/release-0.7.html">Mercury 0.7.3 released.</A><BR>
[Oct 13 1997] <A HREF="download/release-0.7.html">Mercury 0.7.2 released.</A>
    <BR>
[Aug 15 1997] <A HREF="download/release-0.7.html">Mercury 0.7 released.</A><BR>
[Jan 14 1997] <A HREF="download/release-0.6.html">Mercury 0.6.2 released.</A>
    <BR>
[Aug 26 1996] <A HREF="download/release-0.6.html">Mercury 0.6.1 released.</A>
    <BR>
[Aug 2 1996] <A HREF="download/release-0.6.html">Mercury 0.6 released.</A><BR>
[Feb 15 1996] <A HREF="download/release-0.5.html">Mercury 0.5 released.</A><BR>
[Sep 15 1995] <A HREF="download/release-0.4.html">Mercury 0.4 released.</A><BR>
[Jul 18 1995] <A HREF="download/release-0.3.html">Mercury 0.3 released.</A><BR>
