<h1>Mercury Web Site Search</h1>
<hr noshade size=4>
<!-- Search Google -->
<center>
<FORM method=GET action=http://www.google.com/search>
<TABLE bgcolor=#FFFFFF cellspacing=3 border=2>
<tr valign=top><td>
<A HREF=http://www.google.com/search>
<IMG SRC=http://www.google.com/logos/Logo_40wht.gif border=0 ALT=Google
align=middle></A>
</td>
<td>
<INPUT TYPE=text name=q size=31 maxlength=255 value="">
<INPUT type=submit name=sa VALUE="Google Search">
<input type=hidden name=domains
value="www.mercury.csse.unimelb.edu.au"><br><input type=radio name=sitesearch
value=""> Search WWW <input type=radio name=sitesearch
value="www.mercury.csse.unimelb.edu.au" checked> Search Mercury web site<br>
</td></tr></TABLE>
</FORM>
</center>
<!-- Search Google --> 

<hr noshade size=4>
