<h3> What is Mercury? </h3>

Logic programming languages have been around for more than twenty years.
Despite the expected advantages of a very high level programming
language based upon well developed theories of logic over conventional
programming languages (such as C, C++, Pascal and Ada) they have not had
significant impact on the computer industry.
<p> 
Mercury is a new logic/functional programming language, which combines
the clarity and expressiveness of declarative programming with advanced
static analysis and error detection features. Its highly optimized
execution algorithm delivers efficiency far in excess of existing logic
programming systems, and close to conventional programming systems.
Mercury addresses the problems of large-scale program development,
allowing modularity, separate compilation, and numerous
optimization/time trade-offs.
