target: html

ROOT=..
HTML= 	current-release-bugs.html	\
	limitations.html		\
	old-release.html		\
	release.html			\
	release-0.3.html		\
	release-0.4.html		\
	release-0.5.html		\
	release-0.5.1.html		\
	release-0.6.html		\
	release-0.7.html		\
	release-0.7.3.html		\
	release-0.3-bugs.html		\
	release-0.4-bugs.html		\
	release-0.5-bugs.html		\
	release-0.5.1-bugs.html		\
	release-0.6-bugs.html		\
	release-0.7-bugs.html		\
	release-0.3-contents.html	\
	release-0.4-contents.html	\
	release-0.5-contents.html	\
	release-0.6-contents.html	\
	release-0.7-contents.html	\
	rotd.html

current-release-bugs.html: release-0.7-bugs.inc

include ../Makefile.common
