<h2>Email Addresses</h2>

Please send bug reports, enhancement requests and suggestions for
improvement to 
<a href = "mailto:mercury-bugs@cs.mu.oz.au">
mercury-bugs@cs.mu.oz.au</a>.
<p> 
Other inquiries should go to  
<a href = "mailto:mercury@cs.mu.oz.au">
mercury@cs.mu.oz.au</a>.  
<p>
If sending a bug report, please enclose as much information as possible,
including, if possible source code (such as a small test case that
exhibits the bug), any error messages encountered, operating system
version, and configuration information, compiler flags used and Mercury
compiler version. Also, you might want to check the 
<a href="../download/release.html">current release</a> to see if a newer
release is available, or see the 
<a href="../download/current-release-bugs.html">known problems</a>
section to see if the bug has already been reported.

<p> 
You may also be interested in subscribing to the Mercury 
<a href = "mailinglists.html">mailing lists</a>.
