<h2>People Involved</h2>

People who are currently working on the Mercury project
at the University of Melbourne:

<ul>
<li> <a href = "http://www.cs.mu.OZ.AU/~bromage/">Andrew Bromage</a>,
bromage@cs.mu.OZ.AU, MSc student
<li> Mark Brown, dougl@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~conway/">Thomas Conway</a>,
conway@cs.mu.OZ.AU, PhD student
<li> <a href = "http://www.cs.mu.OZ.AU/~trd/">Tyson Dowd</a>,
trd@cs.mu.OZ.AU, PhD student
<li> <a href = "http://www.cs.mu.OZ.AU/~fjh/">Fergus Henderson</a>,
fjh@cs.mu.OZ.AU, research fellow
<li> <a href = "http://www.cs.mu.OZ.AU/~dgj/">David Jeffery</a>,
dgj@cs.mu.OZ.AU, PhD student
<li> <a href = "http://www.cs.mu.OZ.AU/~dmo/">David Overton</a>,
dmo@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~lee/">Lee Naish</a>,
lee@cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~petdr">Peter Ross</a>,
petdr@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~schachte/">Peter Schachte</a>,
schachte@cs.mu.OZ.AU, Lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~zs/">Zoltan Somogyi</a>,
zs@cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~harald/">Harald S&oslash;ndergaard</a>,
harald@cs.mu.OZ.AU, senior lecturer
<li> Simon Taylor, stayl@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~aet/">Bert Thompson</a>,
aet@cs.mu.OZ.AU, research fellow
</ul>

People who have worked on the project in the past,
some of whom are still informally associated with the project:

<ul>
<li> Tibor Benyi, honours student
<li> James Bligh, directed studies student
<li> Waye-Ian Chiew, wchi@students.cs.mu.OZ.AU, summer student
<li> Oliver Hutchinson, ohutch@students.cs.mu.OZ.AU, summer student
<li> Jane Langley, summer student
<li> Peter Malkin, pnmalk@students.cs.mu.OZ.AU, summer student
<li> Bill Peden, honours student
<li> Steven Siew, honours student
<li> Chris Speirs, crs@students.cs.mu.OZ.AU, summer student
<li> Vanessa Teague, vjteag@students.cs.mu.OZ.AU, summer student
</ul>
