<h2>People Involved</h2>

People who are currently working on the Mercury project
at the University of Melbourne:

<ul>
<li> Ralph Becket, rafe@cs.mu.oz.au, research assistant
<li> Mark Brown, dougl@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~trd/">Tyson Dowd</a>,
trd@cs.mu.OZ.AU, PhD student
<li> Julien Fischer, juliensf@cs.mu.oz.au, Honours student
<li> Julian Grady, julianpg@students.cs.mu.oz.au, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~fjh/">Fergus Henderson</a>,
fjh@cs.mu.OZ.AU, research fellow
<li> Paul Incani, paulai@students.cs.mu.oz.au, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~dgj/">David Jeffery</a>,
dgj@cs.mu.OZ.AU, PhD student
<li> <a href = "http://www.cs.mu.OZ.AU/~lee/">Lee Naish</a>,
lee@cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~dmo/">David Overton</a>,
dmo@cs.mu.OZ.AU, PhD student
<li> <a href = "http://www.cs.mu.OZ.AU/~petdr">Peter Ross</a>,
petdr@cs.mu.OZ.AU, MEngSc student
<li> <a href = "http://www.cs.mu.OZ.AU/~schachte/">Peter Schachte</a>,
schachte@cs.mu.OZ.AU, lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~zs/">Zoltan Somogyi</a>,
zs@cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~harald/">Harald S&oslash;ndergaard</a>,
harald@cs.mu.OZ.AU, senior lecturer
<li> Simon Taylor, stayl@cs.mu.OZ.AU, research assistant
<li> Nicolas Watmough, ndw@students.cs.mu.OZ.AU, summer student
<li> Michael Wybrow, mjwybrow@students.cs.mu.OZ.AU, summer student
<li> Lars Yencken, lljy@students.cs.mu.OZ.AU, summer student
</ul>

People who have worked on the project in the past,
some of whom are still informally associated with the project:

<ul>
<li> Tibor Benyi, honours student
<li> James Bligh, directed studies student
<li> Andrew Bromage, MSc student
<li> Levi Cameron, levi@students.cs.mu.oz.au, summer student
<li> Ina Cheng, inch@students.cs.mu.oz.au, summer student
<li> Waye-Ian Chiew, wchi@students.cs.mu.OZ.AU, summer student
<li> <a href = "http://www.mds.rmit.edu.au/~conway/">Thomas Conway</a>,
conway@mds.rmit.edu.au, PhD
<li> Michael Day, summer student
<li> Warwick Harvey, research fellow at Monash University
<li> Oliver Hutchinson, ohutch@students.cs.mu.OZ.AU, summer student
<li> Robert Hutton, summer student
<li> Erwan Jahier, jahier@imag.fr, research assistant at Verimag in Grenoble, France
<li> Robert Jeschofnik, rejj@students.cs.mu.oz.au, directed studies student
<li> Charles Kemp, summer student
<li> Jane Langley, summer student
<li> Peter Malkin, pnmalk@students.cs.mu.OZ.AU, summer student
<li> Simon Mei, xcsm@students.cs.mu.oz.au, summer student
<li> Bill Peden, honours student
<li> Adrian Pellas-Rice, apell@students.cs.mu.oz.au, summer student
<li> Steven Siew, honours student
<li> Chris Speirs, crs@students.cs.mu.OZ.AU, summer student
<li> Vanessa Teague, vjteag@students.cs.mu.OZ.AU, summer student
<li> Bert Thompson, research assistant
<li> Sam Thurairatnam, sthur@students.cs.mu.oz.au, summer student
<li> Geoff Wilson, summer student
</ul>
