<h2>People Involved</h2>

People who are currently working on the Mercury project
at the University of Melbourne:

<ul>
<li> <a href = "http://www.cs.mu.oz.au/~rafe/">Ralph Becket</a>,
rafe at cs.mu.oz.au, research fellow 
<li> Paul Bone, pbone at cs.mu.oz.au, honours student
<li> Mark Brown, mark at cs.mu.oz.au, research assistant 
<li> Julien Fischer, juliensf at cs.mu.oz.au, masters student
<li> Ian MacLarty, maclarty at cs.mu.oz.au, masters student 
<li> <a href = "http://www.cs.mu.OZ.AU/~lee/">Lee Naish</a>,
lee at cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~schachte/">Peter Schachte</a>,
schachte at cs.mu.OZ.AU, lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~zs/">Zoltan Somogyi</a>,
zs at cs.mu.OZ.AU, senior lecturer
<li> <a href = "http://www.cs.mu.OZ.AU/~harald/">Harald S&oslash;ndergaard</a>,
harald at cs.mu.OZ.AU, senior lecturer
<li> Peter Wang, wangp at students.cs.mu.oz.au, honours student

</ul>

People who have worked on the project in the past,
some of whom are still informally associated with the project:

<ul>
<li> Tibor Benyi, honours student
<li> James Bligh, directed studies student
<li> <a href = "http://www.mds.rmit.edu.au/~conway/">Thomas Conway</a>,
conway at mds.rmit.edu.au, PhD
<li> Michael Day, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~trd/">Tyson Dowd</a>,
trd at cs.mu.OZ.AU, PhD student
<li> Paul Incani, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~dgj/">David Jeffery</a>,
dgj at cs.mu.OZ.AU, PhD student
<li> Julian Grady, summer student
<li> Andrew Bromage, MSc student
<li> Levi Cameron, summer student
<li> Ina Cheng, summer student
<li> Waye-Ian Chiew, summer student
<li> Richard Fothergill, richardf at student.cs.mu.oz.au, summer student
<li> Warwick Harvey, research fellow at Monash University
<li> <a href = "http://www.cs.mu.OZ.AU/~fjh/">Fergus Henderson</a>,
fjh at cs.mu.OZ.AU, research fellow
<li> Oliver Hutchinson, summer student
<li> Robert Hutton, summer student
<li> Erwan Jahier, jahier at imag.fr, research assistant at Verimag in Grenoble, France
<li> Darko Jankovic, darkoj at cs.mu.oz.au, summer student
<li> Robert Jeschofnik, directed studies student
<li> Charles Kemp, summer student
<li> Jane Langley, summer student
<li> Peter Malkin, summer student
<li> Simon Mei, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~dmo/">David Overton</a>,
dmo at cs.mu.OZ.AU, PhD student
<li> Bill Peden, honours student
<li> Adrian Pellas-Rice, summer student
<li> <a href = "http://www.cs.mu.OZ.AU/~petdr">Peter Ross</a>,
petdr at cs.mu.OZ.AU, MEngSc student
<li> Steven Siew, honours student
<li> Chris Speirs, summer student
<li> Simon Taylor, stayl at cs.mu.oz.au, research assistant
<li> Vanessa Teague, summer student
<li> Bert Thompson, research assistant
<li> Sam Thurairatnam, summer student
<li> Nicolas Watmough, ndw at students.cs.mu.oz.au, summer student
<li> Geoff Wilson, summer student
<li> Michael Wybrow, mjwybrow at cs.mu.oz.au, summer student
<li> Lars Yencken, summer student
</ul>
